PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX cheminf: <http://semanticscience.org/resource/> 
PREFIX qudt: <http://qudt.org/1.1/schema/qudt#> 
SELECT DISTINCT ?g ?uri 
FROM <http://ops.rsc.org>
FROM <http://www.conceptwiki.org>
FROM <http://www.ebi.ac.uk/chembl>
FROM <http://linkedlifedata.com/resource/drugbank>
FROM_CLAUSE
WHERE {
  VALUES ?g {<http://ops.rsc.org> <http://www.conceptwiki.org> <http://www.ebi.ac.uk/chembl> <http://linkedlifedata.com/resource/drugbank>}
  <INPUT_URI>
    PROP_PATH 
      ?uri
  GRAPH ?g {
    ?uri [] [] 
  }
}
